(**Strategy Module**)

Inductive Strategy : Prop :=
    accreditation
  | adaptability
  | agile_methods
  | agile_methods_assurance
  | agile_methods_scalability
  | anti_tamper
  | armor_vs_weight
  | assertion_checking
  | automated_aids
  | automated_io_validation
  | autonomy_vs_usability
  | certification
  | connectors
  | cost_duration_of_added
  | cost_of_automated_aids
  | domain_architecture_within_domain
  | easiest_first_development
  | encryption
  | encryption_interoperability
  | fallbacks
  | fixed_cost_contracts
  | fmea
  | interoperability_conflicts 
  | lightweight_agility
  | loose_coupling 
  | loose_coupling_for_sustainability
  | many_options
  | modularity
  | modularity_slowdowns
  | multi_domain_architecture_interoperability_conflicts
  | multi_domain_modifiability
  | multi_level_security
  | multi_domain_architecture
  | over_optimizing
  | overhead
  | physical_architecture_or_cyber_architecture
  | product_line_architectures
  | reduced_speed_of_assertion_checking
  | reduced_speed_of_connectors_standards_compliance
  | redundancy
  | rework_cost_savings
  | scalability
  | self_adaptive 
  | self_adaptive_defects
  | service_oriented
  | service_oriented_connectors
  | smart_monitoring
  | spare_capacity
  | spare_capacity_tools_costs
  | staffing_empowering
  | survivability
  | tight_coupling
  | tight_vs_loose_coupling
  | usability_vs_cost_savings
  | usability_vs_security
  | use_software_vs_hardware
  | user_programmability
  | userbprogrammed_interoperability
  | value_prioritizing
  | versatility
  | versatility_vs_usability.